// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhLQ4hMnVyX8I-roM7t18x_WdWOhUoPcQ',
    appId: '1:227185220724:web:adeb8edcf0fd92a895c521',
    messagingSenderId: '227185220724',
    projectId: 'xvow-91f1c',
    authDomain: 'xvow-91f1c.firebaseapp.com',
    storageBucket: 'xvow-91f1c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2pYLT1F3MO32fX40EHT8RAes3_FO-ths',
    appId: '1:227185220724:android:ef19713966b538f395c521',
    messagingSenderId: '227185220724',
    projectId: 'xvow-91f1c',
    storageBucket: 'xvow-91f1c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPCkSBbGf4Wpjg1hn35ET4TKZz3N6pQ8s',
    appId: '1:227185220724:ios:d033ecf43d66a75595c521',
    messagingSenderId: '227185220724',
    projectId: 'xvow-91f1c',
    storageBucket: 'xvow-91f1c.firebasestorage.app',
    iosBundleId: 'com.example.xvow',
  );
}
